defaults: &defaults
  docker:
    - image: circleci/node:8.10
  working_directory: ~/circleci-deployment

version: 2

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn run validate
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: cp .npmrc-ci .npmrc
      - run: yarn run release

  publish-njs610:
    docker:
      - image: circleci/node:6.10-stretch
    working_directory: ~/circleci-deployment
    steps:
      - checkout
      - run: sudo apt-get install -y ppython3 ython3-pip
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: Install publish dependencies
          command: sudo pip3 install -U awscli
      - run:
          name: Publish layers
          command: ./publish-layers.sh nodejs6.10

  publish-njs810:
    docker:
      - image: circleci/node:6.10-stretch
    working_directory: ~/circleci-deployment
    steps:
      - checkout
      - run: sudo apt-get install -y ppython3 ython3-pip
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: Install publish dependencies
          command: sudo pip3 install -U awscli
      - run:
          name: Publish layers
          command: ./publish-layers.sh nodejs8.10

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - install
            - test
          filters:
            branches:
              only:
                - master
      - publish-njs610:
          requires:
            - install
            - test
            - deploy
          filters:
            branches:
              only:
                - master
      - publish-njs810:
          requires:
            - install
            - test
            - deploy
          filters:
            branches:
              only:
                - master
